app/urls.py
from django.urls import path
from django.conf.urls.static import static

from django.conf import settings
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('new_course/', views.new_course, name='course'),
    path('courses/<str:parameter>/', views.category_check, name='category'),
    path('courses/<str:parameter>/<int:course_id>/', views.course_check, name='courses_of_cat'),
    path('new_resource/', views.new_resource, name='resource'),
    path('new_copyright_rule/', views.new_copyright, name='copyright'),
    path('new_category/', views.new_category, name='new_category'),
    path('new_course_of_category/', views.new_category_course, name='new_cat_course'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rubysource/urls.py
from django.contrib import admin
from django.urls import path, include

from app import views

urlpatterns = [
    path('adminisration_of_django_project_rubysource/', admin.site.urls),
    path('site-controller-like-admininistration/', views.admin, name='admin'),
    path('', include('app.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

users/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'users'
urlpatterns = [
    path('login_user/', views.login_user, name="login"),
    path('logout_user/', views.logout_user, name='logout'),
    path('registration_user/', views.registration_user, name='registration')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/app/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Administration Panel</title>
    <style>
        body {
            background-color: #111;
            color: #fff;
            font-family: Arial, sans-serif;
            padding: 20px;
            text-align: center;
        }
        
        a {
            display: block;
            margin: 10px;
            font-size: 85px;
            text-decoration: none;
            color: #ff387a;
            transition: color 0.3s;
        }

        a:hover {
            color: #ff66a0;
        }
    </style>
</head>
<body>
    <a href="{% url 'app:course' %}">New Course</a>
    <a href="{% url 'app:new_category' %}">New Category</a>
    <a href="{% url 'app:new_cat_course' %}">New Category-Course</a>
    <a href="{% url 'app:resource' %}">New Resource</a>
    <a href="{% url 'app:copyright' %}">New Copyright Rule</a>
</body>
</html>

app/templates/app/categories.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <link rel="icon" href="{% static '/img/logoMain.png' %}" />

    <style>
        .category a {
            color: #fff;
            text-decoration: none;
        }
        .category_link  {
            width: 500px;
            height: 350px;
        }
        .section-categories-of-courses-cards {
            flex-wrap: wrap;
        }
        /* Reset default margin and padding */
body, html {
    margin: 0;
    padding: 0;
    height: 100%;
}

/* Create a flex container for the body */
body {
    display: flex;
    flex-direction: column;
}

/* Style the main content */
.content {
    flex: 1;
    padding: 20px;
}

/* Style the footer */
.footer {
    flex-shrink: 0;
    /* background-color: #f0f0f0; */
    padding: 10px;
    text-align: center;
}
body, html {
    margin: 0;
    padding: 0;
    height: 100%;
}

/* Create a flex container for the body */
body {
    display: flex;
    flex-direction: column;
}

/* Style the header, main content, and footer */
header, main, footer {
    padding: 20px;
}

header, footer {
    /* background-color: #f0f0f0; */
    text-align: center;
}

main {
    flex: 1;
}

/* Style the footer links */
.footer-right ul {
    display: flex;
    justify-content: center;
    list-style: none;
}

.footer-right li {
    margin-right: 20px;
}
    </style>
</head>
<body>
    <header>
        <div class="left-header">
            <img class="logo" src="{% static '/img/logoMain.png' %}" alt="logomain">
            <h2 class="logo-text">Rubysource</h2>
            <h6 style="z-index: 1;" class="beta-warning">Beta Test</h6>
        </div>
        <div class="right-header">
            <nav class="nav">
                <ul class="nav_list">
                    <li class="nav-list-item"><a class="nav-list-item-link" href="{% url 'app:index' %}">Home</a></li>
                    {% if user.is_authenticated %}
                        <a class="auth-button" href="{% url 'users:logout' %}">Logout</a>
                    {% else %}
                        <a class="auth-button" href="{% url 'users:login' %}">Login</a>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </header>
    <main>
        <div class="section-categories-of-courses">
            <h2 class="section-categories-of-courses-heading">Which Category Of <span class="courses-word">Courses</span> You Prefer ?</h2>
            <div class="section-categories-of-courses-cards">
                {% for category in categories %}
                    <div class="category">
                            <a class="category_link" href="{% url 'app:courses_of_cat' object.title category.id %}"><h3>{{ category.title }}</h3></a>
                    </div>
                {% endfor %}
        </div>
    </main>
    <footer class="">
        <div class="footer-left">
            <h2 style="margin-left: 0px;margin-right: 16px;" class="creator-name">Made by - <a class="twitter-link" href="#">Vachagan Karapetyan</a></h2>
            <p class="site-description">Lorem ipsum dolor, sit amet consectetur adipisicing elit.</p>
            <div class="small-info">
                <h5 class="app-name">Rubysource</h5>
                <div class="logos">
                    <a target="_blank" href="https://github.com/vachagancode"><img class="social-logo" src="{% static  '/img/twitter logo.png' %}" alt="TwitterLogo"></a>
                    <a target="_blank" href="https://twitter.com/karapetyan_vv"><img class="social-logo" src="{% static '/img/github logo.png' %}" alt="GithubLogo"></a>
                </div>
            </div>
        </div>
        <div class="footer-right">
            <nav class="nav">
                <ul class="nav_list">
                    <li class="nav-list-item"><a class="nav-list-item-link" href="{% url 'app:index' %}">Home</a></li>
                </ul>
            </nav>
        </div>
    </footer>
</body>
</html>

app/templates/app/courses.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <link rel="icon" href="{% static '/img/logoMain.png' %}" />
    <style>

        .courses-cards {
            padding: 0;
        }
        footer {
            margin-top: 15px;
        }
        body, html {
    margin: 0;
    padding: 0;
    height: 100%;
}

/* Create a flex container for the body */
body {
    display: flex;
    flex-direction: column;
}

/* Style the header, main content, and footer */
header, main, footer {
    padding: 20px;
}

header, footer {
    /* background-color: #f0f0f0; */
    text-align: center;
}

main {
    flex: 1;
}

/* Style the footer links */
.footer-right ul {
    display: flex;
    justify-content: center;
    list-style: none;
}

.footer-right li {
    margin-right: 20px;
}
    </style>
</head>
<body>
    <header>
        <div class="left-header">
            <img class="logo" src="{% static '/img/logoMain.png' %}" alt="logomain">
            <h2 class="logo-text">Rubysource</h2>
            <h6 style="z-index: 1;" class="beta-warning">Beta Test</h6>
        </div>
        <div class="right-header">
            <nav class="nav">
                <ul class="nav_list">
                    <li class="nav-list-item"><a class="nav-list-item-link" href="{% url 'app:index' %}">Home</a></li>
                    {% if user.is_authenticated %}
                        <a class="auth-button" href="{% url 'users:logout' %}">Logout</a>
                    {% else %}
                        <a class="auth-button" href="{% url 'users:login' %}">Login</a>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </header>

    <main>
        <div class="section-courses-for-following-category">
            <div style="flex-wrap: wrap;" class="courses-cards">
                {% for course in courses %}
                    <div class="courses-cards-card">
                        <a target="_blank" href="{{ course.course_link }}"><img class="thumbnail" src="{{ course.thumbnail.url }}" alt="thumbnail"></a>

                        <div class="courses-cards-card-info">
                            <h2 class="card-title">{{ course.title }}</h2>
                            <p class="card-description">Short Description: {{ course.description }}</p>
                            <h3 class="course-creator">Course Creator: {{ course.course_creator }}</h3>
                        </div>
                        <a target="_blank" class="youtube-view-button" href="{{ course.course_link }}">View On YouTube -></a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </main>

    <footer style="margin-top: 300px;">
        <div class="footer-left">
            <h2 style="margin-left: 0px;margin-right: 16px;" class="creator-name">Made by - <a class="twitter-link" href="#">Vachagan Karapetyan</a></h2>
            <p class="site-description">Lorem ipsum dolor, sit amet consectetur adipisicing elit.</p>
            <div class="small-info">
                <h5 class="app-name">Rubysource</h5>
                <div class="logos">
                    <a target="_blank" href="https://github.com/vachagancode"><img class="social-logo" src="{% static  '/img/twitter logo.png' %}" alt="TwitterLogo"></a>
                    <a target="_blank" href="https://twitter.com/karapetyan_vv"><img class="social-logo" src="{% static '/img/github logo.png' %}" alt="GithubLogo"></a>
                </div>
            </div>
        </div>
        <div class="footer-right">
            <nav class="nav">
                <ul class="nav_list">
                    <li class="nav-list-item"><a class="nav-list-item-link" href="{% url 'app:index' %}">Home</a></li>
                </ul>
            </nav>
        </div>
    </footer>
</body>
</html>

app/templates/app/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <link rel="icon" href="{% static '/img/logoMain.png' %}" />
    <script src="{% static 'index.js' %}"></script>
    <style>
    .dir-card {
        background-color: #445069;
        color: #fff;
        height: 200px;
        width: 450px;
        border-radius: 45px;
        text-align: center;
        padding-top: 15px;
    }
    .dir-card h2 {
        color: #fff;
        margin-top: 65px;
    }

    .dir-card-link {
        color: #fff;
        margin-top: 35px;
    }

        
    @keyframes rotateHeaderLogo {
        0% {
            transform: rotate(0deg);
        }
        100% {
            transform: rotate(1800deg);
        }
    }

    .logo:hover {
        animation: rotateHeaderLogo 60s infinite;
    }   

    @media screen and (min-width: 768px) {
            .resource {
                width: 50%;
            }
        }

        @media screen and (min-width: 992px) {
            .resource {
                width: 33.33%;
            }
        }
    </style>
</head>
<body>
    <header>
        <div class="left-header">
            <img class="logo" src="{% static '/img/logoMain.png' %}" alt="logomain">
            <h2 class="logo-text">Rubysource</h2>
            <h6 style="z-index: 1;" class="beta-warning">Beta Test</h6>
        </div>
        <div class="right-header">
            <nav class="nav">
                <ul class="nav_list">
                    <li class="nav-list-item"><a class="nav-list-item-link" href="{% url 'app:index' %}">Home</a></li>
                    <li id="courses" class="nav-list-item"><a class="nav-list-item-link" href="#">Courses</a></li>
                    <li id="resources" class="nav-list-item"><a class="nav-list-item-link" href="#">Resources</a></li>
                    <li id="copyright" class="copyright nav-list-item"><a class="nav-list-item-link" href="#">Copyright</a></li>
                    {% if user.is_authenticated %}
                        <a class="auth-button" href="{% url 'users:logout' %}">Logout</a>
                    {% else %}
                        <a class="auth-button" href="{% url 'users:login' %}">Login</a>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </header>
    <main>
        <div class="section-main-info">
                <div class="button-div">
                    <div class="buttons">
                        <a class="info-button-course" href="{% url 'users:login' %}">Login</a>
                        <p class="button-breaker"><br /></p>
                        <a class="info-button" href="{% url 'users:registration' %}">Sign Up</a>
                    </div>
                    <img class="logo-rotating" src="{% static '/img/logoMain.png' %}" alt="logomain">
                </div>
                <div class="heading-text">
                    <span class="rubysource">RUBYSOURCE</span> <br />LEARN ANY SKILL <br />YOU WANT !
                </div>
        </div>
        <div class="section-directions">
            <h2 class="heading-directions">Courses</h2>
            <div class="directions-cards">
                {% for course in courses %}
                <div class="dir-card">
                    <h2><a class="dir-card-link" href="{% url 'app:category' course.title %}">{{ course.title }}</a></h2>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="section-resources">
            <h2 class="heading-resources">Resources</h2>
            <div class="resources-names-links">
                <div class="resources">
                    {% for resource in resources %}
                    <div class="resource">
                        <h3 class="resource-title">{{resource.id}}.{{resource.resource_name}} - <a class="resource-title-link" target="_blank" href="{{ resource.resource_link }}">{{ resource.resource_link }}</a></h3>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="section-copyright">
            <h2 class="copyright-title">Copyright</h2>
            {% for rule in rules %}
                <p class="copyright-rule">- {{ rule.copyright_rule }}</p>
            {% endfor %}
        </div>
    </main>

    <footer>
        <div class="footer-left">
            <h2 class="creator-name">Made by - <a class="twitter-link" href="https://twitter.com/karapetyan_vv">Vachagan Karapetyan</a></h2>
            <p class="site-description">Lorem ipsum dolor, sit amet consectetur adipisicing elit.</p>
            <div class="small-info">
                <h5 class="app-name">Rubysource</h5>
                <div class="logos">
                    <a target="_blank" href="https://github.com/vachagancode"><img class="social-logo" src="{% static  '/img/github logo.png' %}" alt="TwitterLogo"></a>
                    <a target="_blank" href="https://twitter.com/karapetyan_vv"><img class="social-logo" src="{% static '/img/twitter logo.png' %}" alt="GithubLogo"></a>
                </div>
            </div>
        </div>
        <div class="footer-right">
            <nav class="nav">
                <ul class="nav_list">
                    <li class="nav-list-item"><a class="footer-link nav-list-item-link" href="{% url 'app:index' %}">Home</a></li>
                    <!-- <li class="nav-list-item"><a class="footer-link nav-list-item-link" href="#">Courses</a></li> -->
                    <a class="auth-button" href="{% url 'users:login' %}">Login</a>
                </ul>
            </nav>
        </div>
    </footer>
</body>
</html>

app/templates/app/new_category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <style>
        body {
            background-color: #1a1a1a;
            color: #ffffff;
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }

        form {
            background-color: #333;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
            width: 300px;
        }

        input[type="text"],
        button {
            display: block;
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: none;
            background-color: #555;
            color: #fff;
            border-radius: 5px;
        }

        button {
            background-color: #007acc;
            cursor: pointer;
        }

        button:hover {
            background-color: #005ca5;
        }
    </style>
</head>
<body>
    <form action="{% url 'app:new_category' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Category</button>
    </form>
</body>
</html>

app/templates/app/new_category_course.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <style>
        body {
            background-color: #1a1a1a;
            color: #ffffff;
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }

        form {
            background-color: #333;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
            width: 300px;
        }

        input[type="text"],
        button {
            display: block;
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: none;
            background-color: #555;
            color: #fff;
            border-radius: 5px;
        }

        button {
            background-color: #007acc;
            cursor: pointer;
        }

        button:hover {
            background-color: #005ca5;
        }
    </style>
</head>
<body>
    <form action="{% url 'app:new_cat_course' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add category course</button>
    </form>
</body>
</html>

app/templates/app/new_copyright.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <style>
        body {
            background-color: #1a1a1a;
            color: #ffffff;
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }

        form {
            background-color: #333;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
            width: 300px;
        }

        input[type="text"],
        button {
            display: block;
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: none;
            background-color: #555;
            color: #fff;
            border-radius: 5px;
        }

        button {
            background-color: #007acc;
            cursor: pointer;
        }

        button:hover {
            background-color: #005ca5;
        }
    </style>
</head>
<body>
    <form action="{% url 'app:copyright' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Copyright Rule</button>
    </form>
</body>
</html>

app/templates/app/new_course.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <style>
        body {
            background-color: #1a1a1a;
            color: #ffffff;
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }

        form {
            background-color: #333;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
            width: 300px;
        }

        input[type="text"],
        button {
            display: block;
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: none;
            background-color: #555;
            color: #fff;
            border-radius: 5px;
        }

        button {
            background-color: #007acc;
            cursor: pointer;
        }

        button:hover {
            background-color: #005ca5;
        }
    </style>
</head>
<body>
    <form action="{% url 'app:course' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add course</button>
    </form>
</body>
</html>

app/templates/app/new_resource.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <style>
        body {
            background-color: #1a1a1a;
            color: #ffffff;
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }

        form {
            background-color: #333;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
            width: 300px;
        }

        input[type="text"],
        button {
            display: block;
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: none;
            background-color: #555;
            color: #fff;
            border-radius: 5px;
        }

        button {
            background-color: #007acc;
            cursor: pointer;
        }

        button:hover {
            background-color: #005ca5;
        }
    </style>
</head>
<body>
    <form action="{% url 'app:resource' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Resource</button>
    </form>
</body>
</html>